### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by zorgick** [CodeGradox/onehalf-lush#1]
Just wanted to say thank you for your theme! Tested it in complex languages like typescriptreact. What a consistent result! Types remain types, constants are constants everywhere and so on. Even a so popular among treesitters [dracula](https://github.com/Mofiqul/dracula.nvim) theme gave me different colors for same syntax types in different places in the code.

The only suggestion, please, promote your theme! A lot of people enjoy onehalf colorscheme, and you work in this field is robust. With lua configs it became a pain for [some developers](https://github.com/sonph/onehalf/issues/117) to switch to similar treesitter light themes. It would be great if you created a PR in nvim-treesitter repo  to add your theme into the list of suggested. Plus you can create a thread in the r/neovim reddit channel.

**Comment by CodeGradox** [comment]
Thank you for the kind words :heart: Most of the work is done by Lush. I just copied the colorscheme from onehalf.

Sure, I can make a post on Reddit. I updated the readme to include a preview.

**Comment by CodeGradox** [comment]
I posted it on reddit.

https://www.reddit.com/r/neovim/comments/sh8y3w/onehalflush_a_light_colorscheme_based_on_one_half/
